name = "YaoQDNN"
uuid = "634fcfd4-b0f0-4729-9d83-d4b7fce8f79a"
authors = ["Chen Zhao", "Roger-luo"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
